### ISSUE TITLE
Example needs completion

### ISSUE THREAD

**Issue by PhatStraw** [AxialData/date-picker#7]
Submit function in the example console.logs "inputValue" but that value doesn't exist.

const submit = (e) => {
    e.preventDefault()
    // your logic
    console.log(inputValue)
  }
  
  Should we define inputValue?

**Comment by pyleglise** [comment]
Fixed in v0.1.29 !
I just removed the console.log(). It was useless.
Thanx Kevin @PhatStraw ;-)
